/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, PartnerClient, at
* https://www.jitblox.com/project/M6ZSuZpXxQ/partnerclient
*/

export * from './model';

