/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, PartnerClient, at
* https://www.jitblox.com/project/M6ZSuZpXxQ/partnerclient
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-order-actions',
  standalone: true,
  templateUrl: './order-actions.component.html',
  styleUrls: ['./order-actions.component.scss'],
  imports: [CommonModule]
})
export class OrderActionsComponent {

  constructor() {}
}
