/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, PartnerClient, at
* https://www.jitblox.com/project/M6ZSuZpXxQ/partnerclient
*/

import { Routes } from '@angular/router';
import { AppComponent } from './app.component';
import { AdminComponent } from './components/Pages/admin.component';
import { CustomerAddComponent } from './components/Pages/customer-add.component';
import { CustomerSearchComponent } from './components/Pages/customer-search.component';
import { DashboardComponent } from './components/Pages/dashboard.component';
import { DeliveriesComponent } from './components/Pages/deliveries.component';
import { InvoicesComponent } from './components/Pages/invoices.component';
import { OrdersComponent } from './components/Pages/orders.component';

export const routes: Routes = [
  {
    path: 'dashboard',
    component: DashboardComponent
  },
  {
    path: 'orders',
    component: OrdersComponent
  },
  {
    path: 'invoices',
    component: InvoicesComponent
  },
  {
    path: 'deliveries',
    component: DeliveriesComponent
  },
  {
    path: 'customer-search',
    component: CustomerSearchComponent
  },
  {
    path: 'customer-add',
    component: CustomerAddComponent
  },
  {
    path: 'admin',
    component: AdminComponent
  },
  {
    path: 'app',
    component: AppComponent
  },
  {
    path: '',
    redirectTo: '/dashboard',
    pathMatch: 'full'
  }
];
