/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, PartnerClient, at
* https://www.jitblox.com/project/M6ZSuZpXxQ/partnerclient
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ContentPlaceholderComponent } from '../Components/content-placeholder.component';

@Component({
  selector: 'app-customer-add',
  standalone: true,
  templateUrl: './customer-add.component.html',
  imports: [ContentPlaceholderComponent, CommonModule]
})
export class CustomerAddComponent {

  constructor() {}
}
